module.exports = {
  content: ["./index.html", "./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "surface-tint": "#3755c3",
        "on-secondary-fixed-variant": "#3b446e",
        "tertiary-container": "#00563a",
        "outline-variant": "#c4c5d5",
        "on-background": "#191c1d",
        primary: "#00288e",
        "surface-bright": "#f8f9fa",
        outline: "#757684",
        "on-error-container": "#93000a",
        surface: "#f8f9fa",
        tertiary: "#003d27",
        "primary-fixed": "#dde1ff",
        "on-tertiary-container": "#3fd298",
        background: "#f8f9fa",
        secondary: "#525c87",
        "on-tertiary-fixed-variant": "#005236",
        "surface-container-highest": "#e1e3e4",
        "on-primary-fixed": "#001453",
        "surface-variant": "#e1e3e4",
        "on-surface-variant": "#444653",
        "surface-container-lowest": "#ffffff",
        "on-primary": "#ffffff",
        "on-primary-container": "#a8b8ff",
        "surface-container-high": "#e7e8e9",
        "on-error": "#ffffff",
        "primary-fixed-dim": "#b8c4ff",
        "secondary-fixed-dim": "#bbc4f6",
        "tertiary-fixed": "#6ffbbe",
        "on-secondary-container": "#4c5680",
        "on-primary-fixed-variant": "#173bab",
        "on-surface": "#191c1d",
        "on-tertiary": "#ffffff",
        "surface-container-low": "#f3f4f5",
        "on-secondary-fixed": "#0e1840",
        "secondary-fixed": "#dde1ff",
        "on-tertiary-fixed": "#002113",
        "inverse-surface": "#2e3132",
        "inverse-primary": "#b8c4ff",
        "surface-dim": "#d9dadb",
        "error-container": "#ffdad6",
        "secondary-container": "#c3ccfe",
        error: "#ba1a1a",
        "primary-container": "#1e40af",
        "surface-container": "#edeeef",
        "inverse-on-surface": "#f0f1f2",
        "on-secondary": "#ffffff",
        "tertiary-fixed-dim": "#4edea3",
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
    },
  },
  plugins: [],
};
